/* Generated by OpenAI GPT (ChatGPT / Codex), at the user's direction. */
chrome.runtime.onMessage.addListener((message, sender, respond) => {
  if (message?.action !== "openBookmarks" || sender.id !== chrome.runtime.id) return;
  // Only our own content scripts can open the fixed extension page; no URL input.
  let origin;
  try { origin = new URL(sender.url).origin; } catch { return; }
  if (!["https://chatgpt.com", "https://chat.openai.com"].includes(origin)) return;
  chrome.tabs.create({url:chrome.runtime.getURL("bookmarks.html")}, () => {
    respond({ok:!chrome.runtime.lastError});
  });
  return true;
});
