/* Generated by OpenAI GPT (ChatGPT / Codex), at the user's direction. */
(() => {
  "use strict";
  const PREFIX = "texBookmark:";
  const MAX_TEXT = 100000, MAX_TEX = 8000, MAX_IMPORT = 2000;
  function sourceURL(value) {
    try {
      const url = new URL(value);
      if (url.protocol !== "https:" || !["chatgpt.com", "chat.openai.com"].includes(url.hostname) ||
          url.username || url.password || url.port || !/\/c\/[A-Za-z0-9_-]+\/?$/.test(url.pathname)) return "";
      return url.origin + url.pathname;
    } catch { return ""; }
  }
  function validate(value) {
    if (!value || typeof value !== "object" || typeof value.id !== "string" || !/^[\w-]{1,80}$/.test(value.id) ||
        !["answer", "formula"].includes(value.kind) || typeof value.title !== "string" ||
        !value.title.trim() || value.title.length > 120 || typeof value.text !== "string" ||
        !value.text.trim() || value.text.length > (value.kind === "formula" ? MAX_TEX : MAX_TEXT) ||
        !Number.isSafeInteger(value.createdAt) || value.createdAt < 0 || value.createdAt > 8640000000000000) {
      throw new Error("ブックマークの形式または文字数が正しくありません。");
    }
    // Rebuild from known fields: imported HTML, prototypes and arbitrary URLs are never used.
    return {id: value.id, kind: value.kind, title: value.title.trim(), text: value.text,
      createdAt: value.createdAt, sourceUrl: sourceURL(value.sourceUrl),
      sourceTitle: typeof value.sourceTitle === "string" ? value.sourceTitle.slice(0, 200) : "",
      messageId: typeof value.messageId === "string" ? value.messageId.slice(0, 160) : ""};
  }
  function storage(method, argument) {
    return new Promise((resolve, reject) => {
      try {
        chrome.storage.local[method](argument, result => {
          const error = chrome.runtime?.lastError;
          if (error) reject(new Error("保存領域を操作できませんでした。容量不足の場合はバックアップ後に不要な項目を削除してください。"));
          else resolve(result);
        });
      } catch { reject(new Error("拡張機能を更新した場合は、ChatGPTのページを再読み込みしてください。")); }
    });
  }
  async function list() {
    const values = await storage("get", null);
    const records = [];
    for (const [key, value] of Object.entries(values)) {
      if (!key.startsWith(PREFIX)) continue;
      try { const record = validate(value); if (key === PREFIX + record.id) records.push(record); } catch { /* Ignore foreign or malformed keys. */ }
    }
    return records.sort((a, b) => b.createdAt - a.createdAt || a.id.localeCompare(b.id));
  }
  async function save(record) {
    const valid = validate(record);
    await storage("set", {[PREFIX + valid.id]: valid});
    return valid;
  }
  async function get(id) {
    if (!/^[\w-]{1,80}$/.test(id)) return null;
    const result = await storage("get", PREFIX + id);
    try { return validate(result[PREFIX + id]); } catch { return null; }
  }
  function create(fields) { return validate({...fields, id: crypto.randomUUID(), createdAt: Date.now()}); }
  function matches(record, query, kind = "all") {
    return (kind === "all" || record.kind === kind) &&
      `${record.title}\n${record.text}\n${record.sourceTitle}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase());
  }
  function parseBackup(text) {
    if (text.length > 5000000) throw new Error("バックアップは5 MB以内にしてください。");
    let data;
    try { data = JSON.parse(text); } catch { throw new Error("JSONファイルを読み取れません。"); }
    if (data?.format !== "tex-symbol-bookmarks" || data.version !== 1 ||
        !Array.isArray(data.bookmarks) || data.bookmarks.length > MAX_IMPORT) {
      throw new Error("対応するブックマークのバックアップではありません（上限2,000件）。");
    }
    const records = data.bookmarks.map(validate);
    if (new Set(records.map(r => r.id)).size !== records.length) throw new Error("IDが重複しています。");
    return records;
  }
  function renderFormula(tex, target) {
    try {
      if (tex.length > MAX_TEX) throw new Error("too long");
      globalThis.katex.render(tex, target, globalThis.TEX_PREVIEW.options(true));
    } catch { target.textContent = "この式は描画できません。下のTeX原文を利用できます。"; }
  }
  const api = Object.freeze({PREFIX, MAX_TEXT, MAX_TEX, sourceURL, validate, list, save, get, create,
    remove: id => storage("remove", PREFIX + id), matches, parseBackup, renderFormula});
  globalThis.TEX_BOOKMARKS = api;
  if (typeof module === "object" && module.exports) module.exports = api;
})();
