/* Generated by OpenAI GPT (ChatGPT / Codex), at the user's direction. */
(() => {
  "use strict";
  const B = globalThis.TEX_BOOKMARKS;
  const $ = id => document.getElementById(id);
  let records = [], refreshVersion = 0;
  function node(tag, text, className) {
    const el = document.createElement(tag);
    if (text != null) el.textContent = text;
    if (className) el.className = className;
    return el;
  }
  function status(text, error = false) { $("status").textContent = text; $("status").classList.toggle("error", error); }
  function button(text, action) {
    const b = node("button", text); b.type = "button";
    b.addEventListener("click", async () => {
      b.disabled = true;
      try { await action(); } catch (e) { status(e.message, true); } finally { b.disabled = false; }
    });
    return b;
  }
  function card(record) {
    const article = node("article", null, "card");
    article.dataset.id = record.id;
    article.append(node("p", `${record.kind === "formula" ? "数式" : "回答"} · ${new Date(record.createdAt).toLocaleString("ja-JP")}${record.sourceTitle ? " · " + record.sourceTitle : ""}`, "meta"));
    const heading = node("h2", record.title);
    article.append(heading);
    if (record.kind === "formula") {
      const preview = node("div", null, "formula");
      B.renderFormula(record.text, preview); article.append(preview);
    }
    const details = node("details");
    details.open = record.kind === "formula";
    details.append(node("summary", record.kind === "formula" ? "TeX原文" : "保存した回答を表示"), node("pre", record.text));
    article.append(details);
    const actions = node("div", null, "actions");
    actions.append(button(record.kind === "formula" ? "TeXをコピー" : "回答をコピー", async () => {
      try { await navigator.clipboard.writeText(record.text); status("コピーしました。"); }
      catch { details.open = true; throw new Error("コピーできませんでした。原文を選択してコピーしてください。"); }
    }));
    if (record.sourceUrl) {
      const link = node("a", "元の会話を開く");
      link.href = record.sourceUrl + "#tex-bookmark=" + encodeURIComponent(record.id);
      link.target = "_blank"; link.rel = "noopener noreferrer"; actions.append(link);
    }
    const rename = button("名前を変更", () => {
      if (article.querySelector("form")) return;
      const form = node("form", null, "rename-form"), input = node("input");
      input.value = record.title; input.maxLength = 120; input.required = true;
      input.setAttribute("aria-label", "ブックマークの名前");
      const submit = node("button", "変更を保存"); submit.type = "submit";
      form.append(input, submit, button("キャンセル", () => form.remove()));
      form.addEventListener("submit", async event => {
        event.preventDefault(); submit.disabled = true;
        try {
          // Fetch current data so a stale tab cannot overwrite a deleted bookmark.
          const current = await B.get(record.id);
          if (!current) throw new Error("このブックマークは削除されています。");
          await B.save({...current, title: input.value});
          await refresh(); status("名前を変更しました。");
        } catch (e) { status(e.message, true); submit.disabled = false; }
      });
      heading.after(form); input.focus(); input.select();
    });
    const confirmation = node("div", null, "delete-confirm"); confirmation.hidden = true;
    confirmation.append(node("span", "このブックマークを削除しますか？"), button("削除する", async () => {
      await B.remove(record.id); await refresh(); status("削除しました。");
    }), button("やめる", () => { confirmation.hidden = true; }));
    actions.append(rename, button("削除", () => { confirmation.hidden = false; }));
    article.append(actions, confirmation);
    return article;
  }
  function render() {
    const visible = records.filter(r => B.matches(r, $("search").value, $("kind").value));
    $("count").textContent = `${visible.length} 件 / 全 ${records.length} 件`;
    $("list").replaceChildren(...visible.map(card));
    $("empty").hidden = !!visible.length;
    $("empty").textContent = records.length ? "条件に一致するブックマークがありません。" : "まだブックマークはありません。ChatGPTの回答の下にある「回答を保存」「数式を保存」から追加できます。";
  }
  async function refresh() {
    const version = ++refreshVersion, result = await B.list();
    if (version !== refreshVersion) return;
    records = result; render();
  }
  $("search").addEventListener("input", render);
  $("kind").addEventListener("change", render);
  $("export").addEventListener("click", async () => {
    try {
      const latest = await B.list();
      const blob = new Blob([JSON.stringify({format:"tex-symbol-bookmarks",version:1,bookmarks:latest}, null, 2)], {type:"application/json"});
      const url = URL.createObjectURL(blob), link = node("a");
      link.href = url; link.download = `tex-bookmarks-${new Date().toISOString().slice(0,10)}.json`;
      link.click(); setTimeout(() => URL.revokeObjectURL(url), 60000);
      status("バックアップのダウンロードを開始しました。ファイルには保存した回答・数式が含まれます。");
    } catch (e) { status(e.message, true); }
  });
  $("import").addEventListener("click", () => $("import-file").click());
  $("import-file").addEventListener("change", async event => {
    const file = event.target.files[0]; if (!file) return;
    $("import").disabled = true;
    let saved = 0;
    try {
      if (file.size > 5000000) throw new Error("バックアップは5 MB以内にしてください。");
      const incoming = B.parseBackup(await file.text());
      for (const record of incoming) {
        // Preserve existing records, including any titles edited since export.
        if (await B.get(record.id)) continue;
        await B.save(record); saved++;
      }
      status(`${saved} 件を復元しました。同じIDの項目は変更していません。`);
    } catch (e) { status(`${saved} 件を復元済み。${e.message}`, true); }
    finally {
      event.target.value = ""; $("import").disabled = false;
      await refresh().catch(e => status(e.message, true));
    }
  });
  let timer;
  chrome.storage.onChanged.addListener((changes, area) => {
    if (area !== "local" || !Object.keys(changes).some(key => key.startsWith(B.PREFIX))) return;
    clearTimeout(timer); timer = setTimeout(() => refresh().catch(e => status(e.message, true)), 150);
  });
  refresh().catch(e => status(e.message, true));
})();
