/* Generated by OpenAI GPT (ChatGPT / Codex), at the user's direction. */
(() => {
  "use strict";
  const B = globalThis.TEX_BOOKMARKS;
  const ANSWERS = '[data-message-author-role="assistant"]';
  const bars = new WeakMap();
  const styleText = `
    :host { font:13px/1.6 system-ui,sans-serif; color-scheme:light dark; }
    * { box-sizing:border-box; } :host([hidden]),[hidden] { display:none!important; }
    .bar { display:flex; gap:8px; align-items:center; flex-wrap:wrap; padding:12px 0; }
    .floating { max-width:calc(100vw - 32px); padding:10px 12px; border:1px solid #8886; border-radius:12px; background:Canvas; color:CanvasText; box-shadow:0 4px 18px #0002; }
    button,a,input,select { font:inherit; } button { cursor:pointer; }
    button,a { color:inherit; } .bar button,.bar a { background:transparent; border:1px solid #8886; border-radius:7px; padding:4px 9px; text-decoration:none; }
    button:disabled { opacity:.55; cursor:wait; } :focus-visible { outline:3px solid #29a586; outline-offset:2px; }
    dialog { width:min(600px,calc(100vw - 28px)); max-height:85vh; overflow:auto; border:1px solid #8886; border-radius:16px; padding:24px; background:Canvas; color:CanvasText; box-shadow:0 18px 70px #0004; }
    dialog::backdrop { background:#0007; } h2 { font-size:20px; margin:0 0 18px; }
    label { display:block; margin:12px 0 5px; } input,select { width:100%; padding:9px; border:1px solid #8887; border-radius:7px; background:Field; color:FieldText; }
    .preview { padding:18px 0; overflow:auto; font-size:22px; }
    pre { white-space:pre-wrap; overflow-wrap:anywhere; max-height:190px; overflow:auto; font:12px/1.6 ui-monospace,monospace; background:#8881; padding:12px; border-radius:8px; }
    .hint { font-size:12px; opacity:.75; } .actions { display:flex; gap:10px; justify-content:flex-end; }
    .actions button { padding:8px 16px; border:1px solid #8887; border-radius:8px; background:ButtonFace; color:ButtonText; }
    .actions .save { background:#16755c; color:#fff; border-color:#16755c; }
    .status { min-height:1.5em; color:#b34436; }
    .toast { position:fixed; right:20px; bottom:24px; max-width:min(440px,calc(100vw - 40px)); background:#203c31; color:white; border-radius:10px; padding:12px 18px; box-shadow:0 4px 20px #0003; z-index:2147483647; }
  `;
  function node(tag, text, className) {
    const el = document.createElement(tag);
    if (text != null) el.textContent = text;
    if (className) el.className = className;
    return el;
  }
  function shadow(host) {
    const root = host.attachShadow({mode:"open"});
    root.append(node("style", styleText)); return root;
  }
  let ui, dialog, toast, toastTimer;
  function ensureUI() {
    if (ui?.isConnected) return;
    ui = node("div"); ui.id = "tex-bookmark-ui";
    const root = shadow(ui);
    dialog = node("dialog"); dialog.setAttribute("aria-label", "ブックマークを保存");
    toast = node("div", "", "toast"); toast.hidden = true; toast.setAttribute("role", "status");
    root.append(dialog, toast); document.body.append(ui);
  }
  function notify(message) {
    ensureUI(); toast.textContent = message; toast.hidden = false;
    clearTimeout(toastTimer); toastTimer = setTimeout(() => { toast.hidden = true; }, 6500);
  }
  function formulaEntries(answer) {
    const result = [], seen = new Set();
    for (const annotation of answer.querySelectorAll('annotation[encoding="application/x-tex"]')) {
      if (annotation.closest('pre,code,[contenteditable]:not([contenteditable="false"]),#tex-symbol-preview-host,#tex-bookmark-ui,#tex-bookmark-fallback')) continue;
      const tex = annotation.textContent.trim();
      if (tex && !seen.has(tex)) {
        result.push({text:tex, element:annotation.closest('.katex-display,.katex,math') || annotation.parentElement});
        seen.add(tex);
      }
    }
    return result;
  }
  function formulas(answer) { return formulaEntries(answer).map(entry => entry.text); }
  function answerText(answer) {
    const clone = answer.cloneNode(true);
    clone.querySelectorAll(".tex-bookmark-bar,script,style,button,svg,[aria-hidden='true']").forEach(el => el.remove());
    for (const annotation of clone.querySelectorAll('annotation[encoding="application/x-tex"]')) {
      const math = annotation.closest(".katex") || annotation.closest("math");
      if (!math || !clone.contains(math)) continue;
      const display = math.closest(".katex-display") || math.getAttribute("display") === "block";
      math.replaceWith(document.createTextNode((display ? "\n\\[" : "\\(") + annotation.textContent.trim() + (display ? "\\]\n" : "\\)")));
    }
    function walk(el) {
      if (el.nodeType === Node.TEXT_NODE) return el.textContent;
      if (el.nodeType !== Node.ELEMENT_NODE) return "";
      if (el.tagName === "BR") return "\n";
      if (el.tagName === "PRE") return "\n```\n" + el.textContent + "\n```\n";
      if (el.tagName === "CODE") return "`" + el.textContent + "`";
      const text = Array.from(el.childNodes, walk).join("");
      if (el.tagName === "LI") return "\n• " + text + "\n";
      if (["TD", "TH"].includes(el.tagName)) return text + "\t";
      return /^(P|DIV|SECTION|ARTICLE|H[1-6]|UL|OL|BLOCKQUOTE|TR)$/.test(el.tagName) ? "\n" + text + "\n" : text;
    }
    return walk(clone).replace(/[ \t]+\n/g, "\n").replace(/\n{3,}/g, "\n\n").trim();
  }
  function source(answer) {
    const message = answer.closest("[data-message-id]") || answer.querySelector("[data-message-id]");
    return {sourceUrl:B.sourceURL(location.href), sourceTitle:document.title, messageId:message?.getAttribute("data-message-id") || ""};
  }
  function openSave(answer, kind) {
    const entries = kind === "formula" ? formulaEntries(answer) : [{text:answerText(answer), element:answer}];
    const values = entries.map(entry => entry.text);
    if (!values.length || !values[0].trim()) {
      notify(kind === "formula" ? "TeX原文を取得できる数式がありません。回答全体は「回答を保存」で保存できます。" : "保存できる回答がまだありません。"); return;
    }
    ensureUI(); if (dialog.open) return;
    let origin = source(entries[0].element);
    const form = node("form");
    const heading = node("h2", kind === "formula" ? "数式をブックマーク" : "回答をブックマーク");
    const titleLabel = node("label", "名前"), title = node("input");
    title.id = "bookmark-title"; titleLabel.htmlFor = title.id; title.maxLength = 120; title.required = true;
    const preview = node("div", null, "preview"), raw = node("pre");
    const error = node("p", "", "status"); error.setAttribute("role", "status");
    const submit = node("button", "保存", "save"); submit.type = "submit";
    const cancel = node("button", "キャンセル"); cancel.type = "button"; cancel.addEventListener("click", () => dialog.close());
    let text = values[0], titleEdited = false;
    title.addEventListener("input", () => { titleEdited = true; });
    function select(index) {
      const value = values[index];
      origin = source(entries[index].element);
      text = value; raw.textContent = value;
      if (!titleEdited) title.value = value.replace(/\s+/g, " ").slice(0, 90);
      preview.hidden = kind !== "formula";
      if (kind === "formula") B.renderFormula(value, preview);
      const tooLong = value.length > (kind === "formula" ? B.MAX_TEX : B.MAX_TEXT);
      error.textContent = tooLong ? "保存上限を超えています（回答10万文字・数式8,000文字）。" : "";
      submit.disabled = tooLong;
    }
    form.append(heading);
    if (kind === "formula") {
      const label = node("label", `保存する数式（${values.length}個）`), chooser = node("select");
      chooser.id = "bookmark-formula"; label.htmlFor = chooser.id;
      values.forEach((value, i) => { const option = node("option", `${i + 1}. ${value.slice(0, 100)}`); option.value = String(i); chooser.append(option); });
      chooser.addEventListener("change", () => select(Number(chooser.value)));
      form.append(label, chooser);
    }
    const actions = node("div", null, "actions"); actions.append(cancel, submit);
    form.append(titleLabel, title, preview, raw,
      node("p", "選んだ内容をこのブラウザ内に保存します。回答は保存時点の内容です。" + (origin.sourceUrl ? "" : " このページには会話URLがないため、元の会話へのリンクは保存できません。"), "hint"), error, actions);
    form.addEventListener("submit", async event => {
      event.preventDefault(); submit.disabled = true; cancel.disabled = true;
      try {
        await B.save(B.create({kind, title:title.value, text, ...origin}));
        dialog.close(); notify("ブックマークに保存しました。「一覧」から確認できます。");
      } catch (e) { error.textContent = e.message; }
      finally { submit.disabled = false; cancel.disabled = false; }
    });
    select(0); dialog.replaceChildren(form); dialog.showModal(); title.focus(); title.select();
  }
  function listButton() {
    const list = node("button", "一覧"); list.type = "button";
    list.addEventListener("click", () => {
      try {
        chrome.runtime.sendMessage({action:"openBookmarks"}, response => {
          if (chrome.runtime.lastError || !response?.ok) notify("一覧を開けませんでした。拡張アイコンから開くか、ページを再読み込みしてください。");
        });
      } catch { notify("ページを再読み込みしてから、一覧を開いてください。"); }
    });
    return list;
  }
  let fallback, fallbackSave;
  function updateFallback(answers) {
    // Unknown message markup: offer formulas only, never treat the whole page as an answer.
    const count = answers.length ? 0 : formulaEntries(document.body).length;
    if (!count) { if (fallback) fallback.hidden = true; return; }
    if (!fallback?.isConnected) {
      fallback = node("div"); fallback.id = "tex-bookmark-fallback";
      Object.assign(fallback.style, {position:"fixed", right:"16px", bottom:"110px", zIndex:"2147483646"});
      const root = shadow(fallback), bar = node("div", null, "bar floating");
      fallbackSave = node("button"); fallbackSave.type = "button";
      fallbackSave.title = "このページに読み込み済みの数式から選んで保存します";
      fallbackSave.addEventListener("click", () => {
        try { openSave(document.body, "formula"); }
        catch { notify("保存画面を開けませんでした。ページを再読み込みしてください。"); }
      });
      bar.append(fallbackSave, listButton()); root.append(bar); document.body.append(fallback);
    }
    fallbackSave.textContent = `数式を保存（${count}）`;
    fallback.hidden = false;
  }
  function install(answer) {
    if (bars.get(answer)?.isConnected) return;
    const host = node("div"); host.className = "tex-bookmark-bar";
    const root = shadow(host), bar = node("div", null, "bar");
    for (const [kind, label] of [["answer", "☆ 回答を保存"], ["formula", "数式を保存"]]) {
      const button = node("button", label); button.type = "button";
      button.addEventListener("click", () => { try { openSave(answer, kind); } catch { notify("保存画面を開けませんでした。ページを再読み込みしてください。"); } });
      bar.append(button);
    }
    bar.append(listButton()); root.append(bar); answer.append(host); bars.set(answer, host);
  }
  let scanTimer, jump = null, jumpTimer;
  function scan() {
    const answers = Array.from(document.querySelectorAll(ANSWERS));
    for (const answer of answers) install(answer);
    updateFallback(answers);
    if (!jump) return;
    let target = jump.messageId ? answers.find(a => source(a).messageId === jump.messageId) : null;
    // Use an exact saved snippet only when a message ID was unavailable.
    if (!target && !jump.messageId) target = answers.find(a => jump.kind === "formula" ? formulas(a).includes(jump.text) : answerText(a).includes(jump.text.slice(0, 160)));
    if (!target && !jump.messageId && jump.kind === "formula") {
      target = formulaEntries(document.body).find(entry => entry.text === jump.text)?.element;
    }
    if (target) {
      jump = null; clearTimeout(jumpTimer);
      target.scrollIntoView({behavior:"smooth", block:"center"});
      target.animate([{outline:"3px solid #29a586", outlineOffset:"8px"}, {outline:"3px solid transparent", outlineOffset:"8px"}], {duration:3500});
      notify("保存元の回答へ移動しました。");
    }
  }
  async function followBookmark() {
    clearTimeout(jumpTimer); jump = null;
    const match = /^#tex-bookmark=([\w-]{1,80})$/.exec(location.hash); if (!match) return;
    try {
      const record = await B.get(match[1]);
      if (location.hash !== match[0] || !record || record.sourceUrl !== B.sourceURL(location.href)) return;
      jump = record; scan();
      if (jump) jumpTimer = setTimeout(() => { jump = null; notify("保存元の回答がまだ表示されていません。会話内をスクロールして探してください。"); }, 15000);
    } catch (e) { notify(e.message); }
  }
  const observer = new MutationObserver(() => {
    // Do not postpone forever while the site keeps streaming or animating.
    if (!scanTimer) scanTimer = setTimeout(() => { scanTimer = null; scan(); }, 350);
  });
  observer.observe(document.body, {childList:true, subtree:true, characterData:true, attributes:true, attributeFilter:["data-message-author-role"]});
  window.addEventListener("hashchange", followBookmark);
  scan(); followBookmark();
})();
