/* Generated by OpenAI GPT (ChatGPT / Codex), at the user's direction. */
(() => {
  'use strict';
  const core = globalThis.TEX_COMPLETION_CORE;
  let enabled = true, composing = false, host, list, editor, menu = null, session = null, before = null, writing = false, suppressed = '', timer;
  function editorFor(target) {
    if (!(target instanceof Element)) return null;
    if (target instanceof HTMLTextAreaElement) return target.disabled || target.readOnly ? null : target;
    if (!target.isContentEditable) return null;
    let root = target; while(root.parentElement?.isContentEditable) root = root.parentElement;
    return root;
  }
  function state(el) {
    if (!el?.isConnected) return null;
    if (el instanceof HTMLTextAreaElement) return {text:el.value, start:el.selectionStart, end:el.selectionEnd, prefix:el.value.slice(0,el.selectionStart)};
    const sel = window.getSelection();
    if (!sel?.rangeCount) return null;
    const range = sel.getRangeAt(0);
    if (!el.contains(range.startContainer) || !el.contains(range.endContainer)) return null;
    const prefix = document.createRange(); prefix.selectNodeContents(el); prefix.setEnd(range.startContainer, range.startOffset);
    const start = prefix.toString().length; prefix.setEnd(range.endContainer, range.endOffset);
    const leaf = range.startContainer.nodeType === Node.ELEMENT_NODE ? range.startContainer : range.startContainer.parentElement;
    if (leaf.closest('pre,code,[contenteditable="false"]')) return null;
    const block = leaf.closest('p,div,li,blockquote');
    const local = document.createRange(); local.selectNodeContents(block && el.contains(block) ? block : el); local.setEnd(range.startContainer,range.startOffset);
    return {text:el.textContent, start, end:prefix.toString().length, prefix:local.toString()};
  }
  function selectRange(el, start, end) {
    if (el instanceof HTMLTextAreaElement) { el.setSelectionRange(start,end); return true; }
    function point(index, preferNext) {
      const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let node,last,offset=0;
      while((node=walker.nextNode())) {
        if(index<offset+node.length || (!preferNext && index===offset+node.length))return [node,index-offset];
        offset+=node.length;last=node;
      }
      return last && index===offset ? [last,last.length] : null;
    }
    // At a paragraph boundary, a replacement starts in the next text node.
    // Selecting the previous node's end would also delete the paragraph break.
    const a=point(start,start!==end), b=start===end?a:point(end,false);
    if (!a || !b) return false;
    const range=document.createRange(); range.setStart(...a); range.setEnd(...b);
    const sel=window.getSelection(); sel.removeAllRanges(); sel.addRange(range); return true;
  }
  function visibility() { document.dispatchEvent(new Event('tex-completion-visibility')); }
  function hide() { menu=null; if(host) host.hidden=true; visibility(); }
  globalThis.TEX_COMPLETION = {isOpen:()=>!!menu};
  function createUI() {
    if(host?.isConnected) return;
    host=document.createElement('div'); host.id='tex-completion-host'; host.hidden=true;
    host.style.cssText='position:fixed;z-index:2147483610;width:min(360px,calc(100vw - 24px));';
    const shadow=host.attachShadow({mode:'open'}), style=document.createElement('style');
    style.textContent=':host{font:13px/1.5 system-ui,sans-serif;color-scheme:light dark}:host([hidden]){display:none!important}.panel{background:Canvas;color:CanvasText;border:1px solid #8887;border-radius:10px;padding:6px;box-shadow:0 8px 24px #0003}button{display:flex;justify-content:space-between;gap:12px;width:100%;padding:6px 9px;background:transparent;color:inherit;border:0;border-radius:5px;text-align:left;cursor:pointer;font:inherit}button[aria-selected=true]{background:#16755c;color:white}code{font:13px ui-monospace,monospace}.hint{font-size:11px;opacity:.75;padding:6px 9px}';
    const panel=document.createElement('div'); panel.className='panel'; list=document.createElement('div'); list.setAttribute('role','listbox'); list.setAttribute('aria-label','TeX入力候補');
    const hint=document.createElement('div'); hint.className='hint'; hint.textContent='↑↓ 選択 · Tab 挿入 · Esc 閉じる';
    panel.append(list,hint);shadow.append(style,panel);document.body.append(host);
  }
  function position() {
    if(!menu || !editor?.isConnected) return;
    const rect=editor.getBoundingClientRect(), width=window.innerWidth, height=window.innerHeight;
    if(!rect.width || rect.bottom<0 || rect.top>height) { hide(); return; }
    host.style.left=Math.max(12,Math.min(rect.left,width-host.offsetWidth-12))+'px';
    const above=rect.top-host.offsetHeight-8;
    host.style.top=Math.max(8,Math.min(above>=8?above:rect.bottom+8,height-host.offsetHeight-8))+'px';
  }
  function paint() {
    list.replaceChildren();
    menu.items.forEach((item,i)=>{
      const row=document.createElement('button');row.type='button';row.tabIndex=-1;row.setAttribute('role','option');row.setAttribute('aria-selected',String(i===menu.index));
      const name=document.createElement('code'),label=document.createElement('span');name.textContent='\\'+item.name;label.textContent=item.label;row.append(name,label);
      row.addEventListener('pointerdown',event=>event.preventDefault());
      row.addEventListener('click',()=>accept(i));list.append(row);
    }); position();
  }
  function refresh() {
    if (!enabled || composing || writing || !editor || document.activeElement!==editor) { hide(); return; }
    const s=state(editor); if(!s || s.start!==s.end) { hide(); return; }
    const found=core.match(s.prefix,s.text.slice(s.end));
    const signature=s.text+'\0'+s.start;
    if(!found || signature===suppressed) { hide(); return; }
    const items=core.candidates(found.query,globalThis.TEX_SYMBOLS);
    if(!items.length) { hide(); return; }
    const index=menu?.signature===signature ? menu.index : 0;
    createUI();menu={items,index,start:s.start-found.command.length,end:s.end,signature};host.hidden=false;paint();visibility();
  }
  function schedule() { clearTimeout(timer); timer=setTimeout(refresh,30); }
  function updateSession(old, next, from, to) {
    if(!session || old.text!==session.text) { session=null; return; }
    const slot=session.slots[session.index], delta=next.length-old.text.length, inserted=to-from+delta;
    if(from<slot.start || to>slot.end || inserted<0 || next.slice(0,from)!==old.text.slice(0,from) || next.slice(from+inserted)!==old.text.slice(to)) {session=null;return;}
    slot.end+=delta;
    for(let i=session.index+1;i<session.slots.length;i++) {session.slots[i].start+=delta;session.slots[i].end+=delta;}
    session.finish+=delta;session.text=next;
  }
  function accept(index) {
    if(!menu) return;
    const s=state(editor), chosen=menu.items[index], start=menu.start, end=menu.end;
    if(!s || s.text+'\0'+s.start!==menu.signature) {hide();return;}
    const previousSession=session;writing=true;
    try {
      if(!selectRange(editor,start,end)) return;
      document.execCommand('insertText',false,chosen.text);
      const next=state(editor), expected=s.text.slice(0,start)+chosen.text+s.text.slice(end);
      if(!next || next.text!==expected) {session=null;return;}
      session=previousSession;
      if(session) updateSession(s,next.text,start,end);
      if(chosen.slots.length) {
        const slots=chosen.slots.map(slot=>({start:start+slot.start,end:start+slot.end}));
        if(session) session.slots.splice(session.index,1,...slots);
        else session={editor,slots,index:0,text:next.text,finish:start+chosen.text.length};
        const slot=session.slots[session.index];selectRange(editor,slot.start,slot.end);
      }
      suppressed=next.text+'\0'+(start+chosen.text.length);
    } finally {writing=false;before=null;hide();}
  }
  document.addEventListener('focusin',event=>{const next=editorFor(event.target);if(next!==editor){editor=next;session=null;}schedule();},true);
  document.addEventListener('focusout',()=>setTimeout(()=>{if(document.activeElement!==editor){hide();session=null;}},0),true);
  document.addEventListener('beforeinput',event=>{
    if(writing) return;const el=editorFor(event.target);before=el?state(el):null;
    if(session && el!==session.editor) session=null;
    if(!before || !session) return;
    if(before.start===before.end) {
      if(event.inputType==='deleteContentBackward') before.start-=Array.from(before.text.slice(0,before.start)).pop()?.length||0;
      else if(event.inputType==='deleteContentForward') before.end+=Array.from(before.text.slice(before.end))[0]?.length||0;
      else if(!event.inputType?.startsWith('insert')) session=null;
    }
    if(['insertParagraph','insertLineBreak','historyUndo','historyRedo'].includes(event.inputType)) session=null;
  },true);
  document.addEventListener('input',event=>{
    if(writing) return;const el=editorFor(event.target);if(!el)return;
    editor=el;const next=state(el);
    if(session) {if(before && next) updateSession(before,next.text,before.start,before.end);else session=null;}
    before=null;suppressed='';schedule();
  },true);
  document.addEventListener('compositionstart',event=>{if(editorFor(event.target)){composing=true;session=null;hide();}},true);
  document.addEventListener('compositionend',event=>{if(editorFor(event.target)){composing=false;schedule();}},true);
  document.addEventListener('selectionchange',schedule);
  document.addEventListener('keydown',event=>{
    if(!enabled || event.defaultPrevented || composing || event.isComposing || event.keyCode===229 || !editorFor(event.target))return;
    if(event.ctrlKey || event.metaKey || event.altKey) {if(['z','y'].includes(event.key.toLowerCase())){session=null;hide();}return;}
    if(event.key==='Escape' && (menu||session)) {
      const s=state(editor);suppressed=s?s.text+'\0'+s.start:'';session=null;hide();event.preventDefault();event.stopImmediatePropagation();return;
    }
    if(menu && ['ArrowDown','ArrowUp'].includes(event.key)) {
      event.preventDefault();event.stopImmediatePropagation();menu.index=(menu.index+(event.key==='ArrowDown'?1:-1)+menu.items.length)%menu.items.length;paint();return;
    }
    if(event.key!=='Tab') return;
    // Refresh even an existing menu: the prefix may have changed just before Tab.
    if(!event.shiftKey) refresh();
    if(menu && !event.shiftKey) {event.preventDefault();event.stopImmediatePropagation();accept(menu.index);return;}
    if(!session || session.editor!==editor)return;
    const s=state(editor), slot=session.slots[session.index];
    if(!s || s.text!==session.text || s.start<slot.start || s.end>slot.end) {session=null;return;}
    const next=session.index+(event.shiftKey?-1:1);
    if(next<0) {session=null;return;}
    event.preventDefault();event.stopImmediatePropagation();hide();
    if(next>=session.slots.length){selectRange(editor,session.finish,session.finish);session=null;}
    else{session.index=next;const field=session.slots[next];selectRange(editor,field.start,field.end);}
  },true);
  window.addEventListener('resize',position,{passive:true});window.addEventListener('scroll',position,{passive:true,capture:true});
  chrome.storage.local.get({completionEnabled:true},s=>{enabled=s.completionEnabled!==false;});
  chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local'&&changes.completionEnabled){enabled=changes.completionEnabled.newValue!==false;if(!enabled){session=null;hide();}}});
})();
