/* Generated by OpenAI GPT (ChatGPT / Codex), at the user's direction. */
(() => {
  'use strict';
  const templates = [
    ['frac', '分数', '\\frac{${1:a}}{${2:b}}'],
    ['sqrt', '平方根', '\\sqrt{${1:x}}'],
    ['root', 'n乗根', '\\sqrt[${1:n}]{${2:x}}'],
    ['sum', '総和', '\\sum_{${1:n=1}}^{${2:N}} ${3:a_n}'],
    ['prod', '積', '\\prod_{${1:n=1}}^{${2:N}} ${3:a_n}'],
    ['int', '積分', '\\int_{${1:a}}^{${2:b}} ${3:f(x)}\\,d${4:x}'],
    ['lim', '極限', '\\lim_{${1:x\\to 0}} ${2:f(x)}'],
    ['overline', '上線・複素共役', '\\overline{${1:z}}'],
    ['bar', '短い上線', '\\bar{${1:z}}'],
    ['hat', 'ハット', '\\hat{${1:A}}'],
    ['vec', 'ベクトル', '\\vec{${1:v}}'],
    ['mathbf', '太字', '\\mathbf{${1:v}}'],
    ['mathrm', '立体字', '\\mathrm{${1:Re}}'],
    ['mathcal', 'カリグラフィー', '\\mathcal{${1:L}}'],
    ['mathbb', '黒板太字', '\\mathbb{${1:R}}'],
    ['text', '数式中の文章', '\\text{${1:text}}'],
    ['boxed', '枠で囲む', '\\boxed{${1:x}}'],
    ['left', '大きさを合わせる括弧', '\\left(${1:x}\\right)'],
    ['pmatrix', '2×2行列', '\\begin{pmatrix}${1:a} & ${2:b} \\\\ ${3:c} & ${4:d}\\end{pmatrix}'],
    ['bmatrix', '2×2行列［ ］', '\\begin{bmatrix}${1:a} & ${2:b} \\\\ ${3:c} & ${4:d}\\end{bmatrix}'],
    ['aligned', '2行の整列式', '\\begin{aligned}${1:a} &= ${2:b} \\\\ ${3:c} &= ${4:d}\\end{aligned}']
  ];
  function expand(template) {
    let text = '', last = 0; const slots = [];
    for (const match of template.matchAll(/\$\{(\d+):([^}]*)\}/g)) {
      text += template.slice(last, match.index);
      slots.push({order:Number(match[1]), start:text.length, end:text.length + match[2].length});
      text += match[2]; last = match.index + match[0].length;
    }
    text += template.slice(last);
    slots.sort((a,b) => a.order-b.order);
    return {text, slots:slots.map(({start,end})=>({start,end}))};
  }
  function match(prefix, following = '') {
    if (/^[A-Za-z{]/.test(following)) return null;
    const found = /(^|[^\\])(\\([A-Za-z]{1,32}))$/.exec(prefix);
    return found ? {command:found[2], query:found[3]} : null;
  }
  function candidates(query, symbols = {}) {
    const result = templates.filter(([name])=>name.startsWith(query)).map(([name,label,template])=>({name,label,...expand(template)}));
    const names = new Set(templates.map(item=>item[0]));
    for (const name of Object.keys(symbols).sort()) {
      if (!names.has(name) && name.startsWith(query) && name !== query) result.push({name,label:symbols[name],text:'\\'+name,slots:[]});
    }
    return result.slice(0,8);
  }
  const api = {expand, match, candidates, templates};
  globalThis.TEX_COMPLETION_CORE = api;
  if (typeof module === 'object' && module.exports) module.exports = api;
})();
