/* Generated by OpenAI GPT (ChatGPT / Codex), at the user's direction. */
(() => {
  'use strict';
  const MAX_CHARS=8000, MAX_CELLS=1000000;
  function tokens(text, ignoreWhitespace) {
    const result=text.match(/\\[A-Za-z]+|\\[\s\S]|\d+(?:\.\d+)?|[\s\S]/g)||[];
    return ignoreWhitespace?result.filter(t=>!/^\s+$/.test(t)):result;
  }
  function compare(before,after,ignoreWhitespace=true) {
    if(before.length>MAX_CHARS||after.length>MAX_CHARS)throw new Error('比較は各式8,000文字以内にしてください。');
    const a=tokens(before,ignoreWhitespace),b=tokens(after,ignoreWhitespace),left=[],right=[];
    function add(out,text,type){const last=out[out.length-1];if(last?.type===type)last.text+=text;else out.push({text,type});}
    let first=0;while(first<a.length&&first<b.length&&a[first]===b[first]){add(left,a[first],'same');add(right,b[first],'same');first++;}
    let ae=a.length,be=b.length;while(ae>first&&be>first&&a[ae-1]===b[be-1]){ae--;be--;}
    const n=ae-first,m=be-first,coarse=(n+1)*(m+1)>MAX_CELLS;
    let removed=0,added=0;
    if(coarse){for(let i=first;i<ae;i++){add(left,a[i],'removed');removed++;}for(let j=first;j<be;j++){add(right,b[j],'added');added++;}}
    else {
      const width=m+1,dp=new Uint16Array((n+1)*width);
      for(let i=n-1;i>=0;i--)for(let j=m-1;j>=0;j--)dp[i*width+j]=a[first+i]===b[first+j]?1+dp[(i+1)*width+j+1]:Math.max(dp[(i+1)*width+j],dp[i*width+j+1]);
      let i=0,j=0;while(i<n||j<m){
        if(i<n&&j<m&&a[first+i]===b[first+j]){add(left,a[first+i++],'same');add(right,b[first+j++],'same');}
        else if(i<n&&(j===m||dp[(i+1)*width+j]>=dp[i*width+j+1])){add(left,a[first+i++],'removed');removed++;}
        else{add(right,b[first+j++],'added');added++;}
      }
    }
    for(let i=ae;i<a.length;i++)add(left,a[i],'same');for(let j=be;j<b.length;j++)add(right,b[j],'same');
    return {left,right,removed,added,coarse,equal:!removed&&!added};
  }
  const api={tokens,compare,MAX_CHARS};globalThis.TEX_DIFF=api;if(typeof module==='object'&&module.exports)module.exports=api;
})();
