/* Generated by OpenAI GPT (ChatGPT / Codex), at the user's direction. */
(() => {
  'use strict';
  const D = globalThis.TEX_DIFF;
  const css = `
    :host{font:14px/1.6 system-ui,sans-serif;color-scheme:light dark;color:CanvasText}
    *{box-sizing:border-box}[hidden]{display:none!important}
    dialog{width:min(1080px,calc(100vw - 24px));max-height:90vh;overflow:auto;border:1px solid #8886;border-radius:16px;background:Canvas;color:CanvasText;padding:24px;box-shadow:0 18px 70px #0004}
    dialog::backdrop{background:#0007}.workspace{max-width:1080px;margin:auto;background:Canvas;color:CanvasText}
    h1{font-size:22px;margin:0}h2{font-size:16px;margin:0 0 12px}.header,.tools{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}
    .hint{font-size:12px;opacity:.75;margin:8px 0 16px}.grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:16px}
    .column{min-width:0;border:1px solid #8885;border-radius:12px;padding:16px}label{display:block;font-size:12px;margin:10px 0 5px}
    select,textarea,button{font:inherit;color:inherit}select,textarea{width:100%;border:1px solid #8887;border-radius:7px;background:Field;color:FieldText;padding:9px}
    select{min-width:0;text-overflow:ellipsis}textarea{display:block;min-height:112px;resize:vertical;font:13px/1.6 ui-monospace,monospace}
    button{padding:7px 12px;background:transparent;border:1px solid #8887;border-radius:7px;cursor:pointer}:focus-visible{outline:3px solid #29a586;outline-offset:2px}
    .math{min-height:100px;max-height:240px;overflow:auto;padding:24px 8px;font-size:24px}.math math{margin:auto}.math.error{font-size:13px;white-space:pre-wrap;overflow-wrap:anywhere;color:#b33}
    pre{min-height:72px;max-height:240px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;background:#8881;border-radius:7px;padding:12px;margin:5px 0 0;font:13px/1.9 ui-monospace,monospace}
    .removed{background:#fbd9df;color:#821d31;text-decoration:line-through}.added{background:#c6f0d7;color:#125532;text-decoration:underline;text-underline-offset:3px}
    .tools{margin:16px 0 8px}.tools label{font-size:13px;margin:0}.status{font-size:13px;margin:8px 0}.legend{display:flex;gap:14px;font-size:12px}.legend span{padding:1px 5px;border-radius:3px}
    @media(max-width:650px){dialog{padding:16px}.grid{grid-template-columns:minmax(0,1fr)}.column{padding:12px}.math{min-height:76px;padding:16px 4px}}
  `;
  function node(tag, text, className) {const n=document.createElement(tag);if(text!=null)n.textContent=text;if(className)n.className=className;return n;}
  function button(text, action) {const n=node('button',text);n.type='button';n.addEventListener('click',action);return n;}
  function mount(root, values=[], selected='', close) {
    values=[...new Set(values.filter(v=>typeof v==='string'&&v.trim()))];
    const box=node('section',null,'workspace'), header=node('div',null,'header'), title=node('h1','数式の差分比較');title.id='tex-diff-title';
    header.append(title);if(close)header.append(button('閉じる',close));
    box.append(header,node('p','式Aと式Bのプレビュー・TeXの差分を確認できます。数学的な同値性は判定しません。','hint'));
    const grid=node('div',null,'grid'), fields=[];let timer;
    const first=Math.max(0,values.indexOf(selected));
    for(let i=0;i<2;i++) {
      const name=i?'B':'A', column=node('section',null,'column');column.append(node('h2',`式${name}`));
      const chooser=node('select');chooser.id=`diff-choice-${name}`;
      const custom=node('option','直接入力');custom.value='';chooser.append(custom);
      values.forEach((v,j)=>{const option=node('option',`${j+1}. ${v.length>140?v.slice(0,140)+'…':v}`);option.value=String(j);chooser.append(option);});
      const choiceLabel=node('label',`チャット内の式${name}`);choiceLabel.htmlFor=chooser.id;
      if(values.length)column.append(choiceLabel,chooser);
      const input=node('textarea');input.id=`diff-input-${name}`;input.spellcheck=false;input.placeholder=i?'例: x^2 - 2x + 1':'例: x^2 + 2x + 1';
      const label=node('label',`TeX ${name}`);label.htmlFor=input.id;
      const preview=node('div',null,'math');preview.setAttribute('aria-label',`式${name}のプレビュー`);
      const raw=node('pre');raw.setAttribute('aria-label',`式${name}のTeX差分`);
      column.append(label,input,preview,node('label',i?'TeX差分（追加）':'TeX差分（削除）'),raw);grid.append(column);
      const initial=i?(values.findIndex((_,j)=>j!==first)):first;
      chooser.value=initial>=0&&values[initial]!=null?String(initial):'';input.value=chooser.value===''?'':values[initial];
      chooser.addEventListener('change',()=>{input.value=chooser.value===''?'':values[Number(chooser.value)];render();});
      input.addEventListener('input',()=>{const found=values.indexOf(input.value);chooser.value=found<0?'':String(found);clearTimeout(timer);timer=setTimeout(render,120);});
      fields.push({input,chooser,preview,raw});
    }
    const tools=node('div',null,'tools'), ignore=node('input');ignore.type='checkbox';ignore.checked=true;ignore.id='diff-ignore-space';
    const ignoreLabel=node('label');ignoreLabel.append(ignore,document.createTextNode(' 空白・改行の違いを無視'));ignore.addEventListener('change',render);
    tools.append(ignoreLabel,button('AとBを入れ替え',()=>{
      const [a,b]=fields;[a.input.value,b.input.value]=[b.input.value,a.input.value];[a.chooser.value,b.chooser.value]=[b.chooser.value,a.chooser.value];render();
    }));
    const status=node('p',null,'status');status.setAttribute('role','status');status.setAttribute('aria-live','polite');
    const legend=node('div',null,'legend');legend.append(node('span','削除：取り消し線','removed'),node('span','追加：下線','added'));
    box.append(grid,tools,status,legend,node('p','比較は各式8,000文字まで。文字・数値・TeXコマンドを単位に比較します。空白を無視する場合、差分欄の空白も省略します（\\text 内の空白も対象）。','hint'));
    root.append(box);
    function render() {
      clearTimeout(timer);
      let tooLong=false;
      for(const f of fields) {
        const value=f.input.value;f.preview.classList.remove('error');f.raw.replaceChildren();
        if(value.length>D.MAX_CHARS){f.preview.textContent='8,000文字を超えているため表示できません。';f.preview.classList.add('error');tooLong=true;}
        else if(!value.trim())f.preview.textContent='数式を入力してください';
        else {
          try{globalThis.katex.render(globalThis.TEX_PREVIEW.normalize(value),f.preview,globalThis.TEX_PREVIEW.options(true));}
          catch{f.preview.textContent='プレビューできません（入力途中・未対応のTeX）。原文の差分は下に表示します。';f.preview.classList.add('error');}
        }
      }
      if(tooLong){status.textContent='比較は各式8,000文字以内にしてください。';return;}
      const result=D.compare(fields[0].input.value,fields[1].input.value,ignore.checked);
      [result.left,result.right].forEach((runs,i)=>runs.forEach(run=>fields[i].raw.append(node('span',run.text,run.type))));
      status.textContent=!fields.some(f=>f.input.value.trim())?'比較する2つの式を入力してください。':result.equal?(ignore.checked?'空白・改行を除くTeXは一致しています。':'TeXは完全に一致しています。'):`削除 ${result.removed} 単位 ／ 追加 ${result.added} 単位`;
      if(result.coarse)status.textContent+=' — 変更が大きいため、変更範囲をまとめて表示しています。';
    }
    render();return ()=>{clearTimeout(timer);box.remove();};
  }
  let host,dialog,dispose;
  function open(values,selected) {
    if(!host?.isConnected) {
      host=node('div');host.id='tex-diff-host';const shadow=host.attachShadow({mode:'open'});shadow.append(node('style',css));
      dialog=node('dialog');dialog.setAttribute('aria-labelledby','tex-diff-title');shadow.append(dialog);document.body.append(host);
      dialog.addEventListener('close',()=>{dispose?.();dispose=null;});
    }
    dispose?.();dispose=mount(dialog,values,selected,()=>dialog.close());if(!dialog.open)dialog.showModal();
  }
  globalThis.TEX_DIFF_UI={open,mount:(root)=>{root.append(node('style',css));return mount(root);}};
})();
