/* Shared between the isolated content script and the extension popup. */
globalThis.TEX_SYMBOLS = Object.freeze({
  alpha: "α", beta: "β", gamma: "γ", delta: "δ", epsilon: "ϵ", varepsilon: "ε",
  zeta: "ζ", eta: "η", theta: "θ", vartheta: "ϑ", iota: "ι", kappa: "κ",
  varkappa: "ϰ", lambda: "λ", mu: "μ", nu: "ν", xi: "ξ", omicron: "ο",
  pi: "π", varpi: "ϖ", rho: "ρ", varrho: "ϱ", sigma: "σ", varsigma: "ς",
  tau: "τ", upsilon: "υ", phi: "ϕ", varphi: "φ", chi: "χ", psi: "ψ", omega: "ω",
  Gamma: "Γ", Delta: "Δ", Theta: "Θ", Lambda: "Λ", Xi: "Ξ", Pi: "Π",
  Sigma: "Σ", Upsilon: "Υ", Phi: "Φ", Psi: "Ψ", Omega: "Ω",
  infty: "∞", partial: "∂", nabla: "∇", hbar: "ℏ", ell: "ℓ", wp: "℘",
  Re: "ℜ", Im: "ℑ", aleph: "ℵ", emptyset: "∅", varnothing: "∅",
  pm: "±", mp: "∓", times: "×", div: "÷", cdot: "⋅", ast: "∗", star: "⋆",
  circ: "∘", bullet: "•", otimes: "⊗", oplus: "⊕", ominus: "⊖", odot: "⊙",
  neq: "≠", ne: "≠", leq: "≤", le: "≤", geq: "≥", ge: "≥",
  ll: "≪", gg: "≫", sim: "∼", simeq: "≃", approx: "≈", equiv: "≡",
  cong: "≅", propto: "∝", prec: "≺", succ: "≻", preceq: "⪯", succeq: "⪰",
  in: "∈", notin: "∉", ni: "∋", subset: "⊂", supset: "⊃", subseteq: "⊆",
  supseteq: "⊇", nsubseteq: "⊈", nsupseteq: "⊉", cup: "∪", cap: "∩",
  setminus: "∖", sqcup: "⊔", sqcap: "⊓", uplus: "⊎",
  forall: "∀", exists: "∃", nexists: "∄", neg: "¬", land: "∧", lor: "∨",
  wedge: "∧", vee: "∨", top: "⊤", bot: "⊥", perp: "⊥", parallel: "∥",
  vdash: "⊢", dashv: "⊣", models: "⊨", therefore: "∴", because: "∵",
  to: "→", gets: "←", rightarrow: "→", leftarrow: "←", leftrightarrow: "↔",
  Rightarrow: "⇒", Leftarrow: "⇐", Leftrightarrow: "⇔", implies: "⇒", iff: "⇔",
  mapsto: "↦", hookrightarrow: "↪", hookleftarrow: "↩", longrightarrow: "⟶",
  longleftarrow: "⟵", longleftrightarrow: "⟷", longmapsto: "⟼",
  uparrow: "↑", downarrow: "↓", updownarrow: "↕", nearrow: "↗", searrow: "↘",
  sum: "∑", prod: "∏", coprod: "∐", int: "∫", iint: "∬", iiint: "∭", oint: "∮",
  sqrt: "√", angle: "∠", degree: "°", prime: "′", dagger: "†", ddagger: "‡",
  langle: "⟨", rangle: "⟩", lceil: "⌈", rceil: "⌉", lfloor: "⌊", rfloor: "⌋",
  ldots: "…", dots: "…", cdots: "⋯", vdots: "⋮", ddots: "⋱",
  mathbbR: "ℝ", mathbbC: "ℂ", mathbbZ: "ℤ", mathbbN: "ℕ", mathbbQ: "ℚ",
  mathbbH: "ℍ", mathbbP: "ℙ"
});
